<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>preview</LangVersion>
    <Version>4.0.2</Version>
    <ResolveAssemblyReferencesSilent>true</ResolveAssemblyReferencesSilent>
    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>low</NuGetAuditLevel>
    <Verify_SponsorshipExemption>OpenSource</Verify_SponsorshipExemption>
    <Verify_SponsorshipExemptionUntil>2027-08</Verify_SponsorshipExemptionUntil>
  </PropertyGroup>
</Project>
