<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
    <DisableFody>true</DisableFody>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'" />
    <PackageReference Include="FodyHelpers" />
    <PackageReference Include="System.Security.Permissions" />
    <PackageReference Include="System.Threading.AccessControl" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="Verify.TUnit" />
    <ProjectReference Include="..\BadCaseAssembliesToProcess\ClassWithOperatorsOptOutButWeavingInstruction\ClassWithOperatorsOptOutButWeavingInstruction.csproj" />
    <ProjectReference Include="..\BadCaseAssembliesToProcess\ClassWithoutOperators\ClassWithoutOperators.csproj" />
    <ProjectReference Include="..\BadCaseAssembliesToProcess\ClassWithoutWeavingInstruction\ClassWithoutWeavingInstruction.csproj" />
    <ProjectReference Include="..\BadCaseAssembliesToProcess\StructWithOperatorsOptOutButWeavingInstruction\StructWithOperatorsOptOutButWeavingInstruction.csproj" />
    <ProjectReference Include="..\BadCaseAssembliesToProcess\StructWithoutWeavingInstruction\StructWithoutWeavingInstruction.csproj" />
    <ProjectReference Include="..\BadCaseAssembliesToProcess\StructWithoutOperators\StructWithoutOperators.csproj" />
    <ProjectReference Include="..\Equals.Fody\Equals.Fody.csproj" />
    <ProjectReference Include="..\Equals\Equals.csproj" />
    <ProjectReference Include="..\AssemblyToProcess\AssemblyToProcess.csproj" />
    <ProjectReference Include="..\AssemblyToProcessWithoutReference\AssemblyToProcessWithoutReference.csproj" />
  </ItemGroup>
</Project>
